services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      KAFKAJS_NO_PARTITIONER_WARNING: 1
    ports:
      - 3000:3000
    depends_on:
      - mongodb
      - kafka
  mongodb:
    image: mongodb/mongodb-community-server
    restart: always
    ports:
      - 27018:27017
    volumes:
      - mongodb-data:/var/lib/mongodb/data
  kafka:
    image: apache/kafka
    ports:
      - 9092:9092
volumes:
  mongodb-data: