services:
  server:
    build:
      context: .
    environment:
      - KAFKAJS_NO_PARTITIONER_WARNING=1
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - mongodb
      - kafka
  mongodb:
    image: mongodb/mongodb-community-server
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/var/lib/mongodb/data
  kafka:
    image: apache/kafka
    ports:
      - 9092:9092
volumes:
  mongodb-data:
networks:
  default:
    driver: bridge
    name: my-network