services:
  server:
    build:
      context: .
    environment:
      - KAFKAJS_NO_PARTITIONER_WARNING=1
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - mongodb
      - kafka
  mongodb:
    image: mongodb/mongodb-community-server
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/var/lib/mongodb/data
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.2
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: '2181'
      ZOOKEEPER_TICK_TIME: '2000'
      KAFKA_OPTS: '-Djava.security.auth.login.config=/etc/kafka/server-jaas.conf -Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider'
    volumes:
      - ./testHelpers/kafka/server-jaas.conf:/etc/kafka/server-jaas.conf:ro,z
volumes:
  mongodb-data:
networks:
  default:
    driver: bridge
    name: my-network